# -*- mode: ruby -*-
# vi: set ft=ruby :

hostconfig = {
  :name => "bionic64",
  :box => "ubuntu/bionic64",
  :cpus => "4",
  :mem => "8192",
  :ip => "1.100.201.2"
}

Vagrant.configure("2") do |config|
  config.vm.hostname = hostconfig[:name]
  config.vm.box = hostconfig[:box]
  config.vm.box_check_update = false
  config.vm.synced_folder "/tmp", "/mnt/tmp"
  config.vm.synced_folder "./data", "/home/vagrant/data"
  config.vm.network :private_network, ip: hostconfig[:ip]
  config.vm.network "public_network", type: "dhcp", bridge: [
    "en1: Wi-Fi (AirPort)",
  ]
  config.disksize.size = '80GB'
  config.vm.provider 'virtualbox' do |vb|
    vb.name = hostconfig[:name]
    vb.memory = hostconfig[:mem].to_i
    vb.cpus = hostconfig[:cpus].to_i
  end

  config.vm.provision 'shell', path: 'provision_dev.sh'
end
